#!/bin/sh

#set -e  <-- bomb on errors... this options sucks

case "$1" in
  purge)
    rm -rf /var/lib/flashback 2> /dev/null
    rm -f /var/run/flashback.pid 2> /dev/null
    #rm -f /var/log/flashback.log 2> /dev/null
    update-rc.d flashback remove >/dev/null
    ;;
esac

exit 0

