#!/bin/sh

if [ -x "/etc/init.d/flashback" ]; then
    if [ ! -e "/etc/init/flashback.conf" ]; then
        update-rc.d flashback defaults >/dev/null
    fi
    invoke-rc.d flashback start || exit $?
fi

